"""Docs: https://InovaFiscaliza.github.io/rfdatahub/constants.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_constants.ipynb.

# %% auto #0
__all__ = ['TIMEOUT', 'RELATORIO_SRD', 'ESTACAO', 'MALHA_IBGE', 'FILES', 'PATH_NAV', 'PATH_COM', 'VOR_ILS_DME', 'CHANNELS',
           'IBGE_MUNICIPIOS', 'IBGE_POLIGONO', 'MONGO_TELECOM', 'MONGO_SRD', 'MONGO_SMP', 'SQL_STEL',
           'SQL_VALIDA_COORD', 'REGEX_ESTADOS', 'RE_BW', 'MIN_LAT', 'MAX_LAT', 'MIN_LONG', 'MAX_LONG']

# %% ../nbs/00_constants.ipynb #2301aae9
import re
from pathlib import Path

# %% ../nbs/00_constants.ipynb #1cf006fc-90f6-415b-873d-923faf23b6e2
TIMEOUT = 5
RELATORIO_SRD = "http://sistemas.anatel.gov.br/se/eApp/reports/b/srd/resumo_sistema.php?id={}&state={}"
ESTACAO = "http://sistemas.anatel.gov.br/se/public/view/b/srd.php?wfid=estacoes&id={}"
MALHA_IBGE = "https://geoftp.ibge.gov.br/organizacao_do_territorio/malhas_territoriais/malhas_municipais/municipio_2025/Brasil/BR/BR_Municipios_2025.zip"
FILES = Path(__file__).parent / "datasources" / "arquivos"
PATH_NAV = FILES / "VHF_NAV.csv"
PATH_COM = FILES / "VHF_COM.csv"
VOR_ILS_DME = FILES / "VOR_ILS_DME_Channel.csv"
CHANNELS = FILES / "canalizacao_smp.csv"
IBGE_MUNICIPIOS = FILES / "municipios.csv"
IBGE_POLIGONO = FILES / "BR_Municipios_2025" / "BR_Municipios_2025.shp"


# %% ../nbs/00_constants.ipynb #2cc85745
MONGO_TELECOM = {
    "$and": [
        {"DataExclusao": {"$in": [None, ""]}},
        {"DataMotivoExclusao": {"$in": [None, ""]}},
        {"DataValidade": {"$nin": ["", None]}},
        {"Status.state": "LIC-LIC-01"},
        {"NumServico": {"$nin": ["010", "045", "171", "450", "750", "", None]}},
        {"FreqTxMHz": {"$nin": [None, "", 0], "$type": 1.0}},
        {"CodMunicipio": {"$nin": [None, ""]}},
        {"NumFistel": {"$nin": [None, ""]}},
        {"CodTipoClasseEstacao": {"$nin": [None, ""]}},
        {"DesignacaoEmissao": {"$nin": [None, ""]}},
    ]
}


MONGO_SRD = {
    "$and": [
        {"frequency": {"$nin": [None, "", 0], "$type": 1.0}},
        {"srd_planobasico.CodMunicipio": {"$nin": [None, ""]}},
        {"NumFistel": {"$nin": [None, ""]}},
    ]
}

MONGO_SMP = {
    "$and": [
        {"DataExclusao": {"$in": [None, ""]}},
        {"DataMotivoExclusao": {"$in": [None, ""]}},
        {"DataValidade": {"$nin": ["", None]}},
        {"Status.state": "LIC-LIC-01"},
        {"NumServico": "010"},
        {"FreqTxMHz": {"$nin": [None, "", 0], "$type": 1.0}},
        {"CodMunicipio": {"$nin": [None, ""]}},
        {"NumFistel": {"$nin": [None, ""]}},
        {"CodTipoClasseEstacao": {"$nin": [None, ""]}},
        {"DesignacaoEmissao": {"$nin": [None, ""]}},
        {"Tecnologia": {"$nin": [None, ""]}},
    ]
}

# %% ../nbs/00_constants.ipynb #03f4d8fb
SQL_STEL = """
select 
  distinct f.MedTransmissaoInicial as 'Frequência', 
  uf.SiglaUnidadeFrequencia as 'Unidade', 
  d.CodClasseEmissao as 'Classe_Emissão', 
  d.SiglaLarguraEmissao as 'Largura_Emissão', 
  ce.CodTipoClasseEstacao as 'Classe', 
  e.NumServico as 'Serviço', 
  ent.NomeEntidade as 'Entidade', 
  h.NumFistel as 'Fistel', 
  e.NumEstacao as 'Estação', 
  mu.NomeMunicipio as 'Município',
  mu.CodMunicipio as Código_Município,
  e.SiglaUf as 'UF', 
  e.MedLatitudeDecimal as 'Latitude', 
  e.MedLongitudeDecimal as 'Longitude', 
  c.DataValidadeRadiofrequencia as 'Validade_RF' 
from 
  estacao e 
  left join contrato c on e.IdtContrato = c.Idtcontrato 
  left join frequencia f on f.IdtEstacao = e.IdtEstacao 
  left join CLASSEESTACAO ce on ce.IdtFrequencia = f.IdtFrequencia 
  left join DESIGNACAOEMISSAO d on d.IdtClasseEstacao = ce.IdtClasseEstacao 
  left join HABILITACAO h on h.IdtHabilitacao = c.IdtHabilitacao 
  left join entidade ent on ent.IdtEntidade = h.IdtEntidade 
  left join endereco en on en.IdtEstacao = e.IdtEstacao 
  left join Municipio mu on mu.CodMunicipio = en.CodMunicipio 
  left join Servico s on s.NumServico = h.NumServico 
  and s.IdtServicoAreaAtendimento = 4 
  left join UnidadeFrequencia uf on uf.IdtUnidadeFrequencia = f.IdtUnidadeTransmissao 
where 
  h.NumServico <> '010' 
  and e.DataExclusao is null 
  and e.IndStatusEstacao = 'L' 
  and mu.CodMunicipio is not null
  and f.MedTransmissaoInicial is not null 
  and f.CodStatusRegistro = 'L' 
  and c.DataValidadeRadiofrequencia is not null 
"""

# %% ../nbs/00_constants.ipynb #f0b3f604
SQL_VALIDA_COORD = """
    SELECT 
        mun.NO_MUNICIPIO 
        , mun.NU_LONGITUDE 
        , mun.NU_LATITUDE         
        , CONVERT(int, 
            (mun.GE_POLIGONO.STIntersects(geometry::STGeomFromText(
                'POINT({} {})', 
                mun.GE_POLIGONO.STSrid)
            )) 
        )AS COORD_VALIDA
    from 
        CORPORATIVO.dbo.TB_IBGE_MUNICIPIO mun
    WHERE
        MUN.CO_MUNICIPIO = {}
"""

# %% ../nbs/00_constants.ipynb #ff102e0d
REGEX_ESTADOS = f'({"|".join(ESTADOS)})'
RE_BW = re.compile(r"^(\d{1,3})([HKMG])(\d{0,2})(\w{0,3})")

# %% ../nbs/00_constants.ipynb #c168493d
MIN_LAT = -33.7509907  # Arroio Chuy RS
MAX_LAT = 5.2718317  # Monte Caburaí RR
MIN_LONG = -73.80658592032779
MAX_LONG = -32.377816
