# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/01b_base.ipynb.

# %% auto 0
__all__ = ["Base", "DatabaseConnector"]

# %% ../../nbs/01b_base.ipynb 3
import json
import re
from abc import ABC, abstractmethod
from dataclasses import dataclass
from functools import cached_property, partial
from typing import Tuple, Union, Any, Optional, Dict, List

import pandas as pd
from rich import print as pp
from dotenv import find_dotenv, load_dotenv
from fastcore.xtras import Path, listify
from pyarrow import ArrowInvalid, ArrowTypeError
from tqdm.auto import tqdm

from ..constants import BW, RE_BW

# %% ../../nbs/01b_base.ipynb 4
load_dotenv(find_dotenv(), override=True)
tqdm.pandas()
pd.options.mode.copy_on_write = True


# %% Abstract DatabaseConnector interface
class DatabaseConnector(ABC):
    """Abstract interface for database connectors"""
    
    @abstractmethod
    def connect(self):
        """Establish a connection to the database"""
        pass
    
    @abstractmethod
    def extract_data(self, query: Union[str, dict], **kwargs) -> pd.DataFrame:
        """Extract data from the database using the provided query"""
        pass


# %% ../../nbs/01b_base.ipynb 6
@dataclass
class Base:
    """Base class for data extraction with a deeper interface"""
    
    folder: Union[str, Path] = Path(__file__).parent / "arquivos" / "saida"
    read_cache: bool = False
    db_connector: Optional[DatabaseConnector] = None

    def __post_init__(self):
        """Initialize the Base class with common setup"""
        if self.db_connector is None:
            raise ValueError("A DatabaseConnector instance must be provided")

    def _read(self, stem: str, backend: str = "pyarrow") -> pd.DataFrame:
        """Read a dataframe from a parquet file"""
        file = Path(f"{self.folder}/{stem}.parquet")
        try:
            return pd.read_parquet(file, dtype_backend=backend).astype(
                "string", copy=False
            )
        except (ArrowInvalid, FileNotFoundError) as e:
            raise ValueError(f"Error when reading {file}") from e

    def _save(
        self, df: pd.DataFrame, folder: Union[str, Path], stem: str
    ) -> pd.DataFrame:
        """Save a dataframe to a parquet file"""
        folder = Path(folder)
        folder.mkdir(parents=True, exist_ok=True)
        try:
            file = Path(f"{folder}/{stem}.parquet")
            df.astype("category").to_parquet(file, index=False, engine="pyarrow")
        except (ArrowInvalid, ArrowTypeError) as e:
            raise Exception("Não foi possível salvar o arquivo parquet") from e
        return df

    @cached_property
    def df(self) -> pd.DataFrame:
        """Cached property to get the processed dataframe"""
        try:
            return self._read(self.stem)
        except (ArrowInvalid, FileNotFoundError) as e:
            raise ValueError(
                f"Não foi possível ler o arquivo parquet {self.stem}"
            ) from e

    @staticmethod
    def parse_bw(
        bw: str,  # Designação de Emissão (Largura + Classe) codificada como string
    ) -> Tuple[Union[str, Any], Union[str, Any]]:  # Largura e Classe de Emissão
        """Parse the bandwidth string"""
        if match := re.match(RE_BW, bw):
            multiplier = BW[match[2]]
            if mantissa := match[3]:
                number = float(f"{match[1]}.{mantissa}")
            else:
                number = float(match[1])
            classe = str(match[4])
            if not classe:
                classe = pd.NA
            return str(multiplier * number), classe
        return pd.NA, pd.NA

    @staticmethod
    def register_log(
        df: pd.DataFrame,
        processing: str,
        column: Union[str, None] = None,
        row_filter: Union[pd.Series, None] = None,
    ):
        """Register a log in the dataframe"""
        if row_filter is None:
            row_filter = pd.Series(True, index=df.index)
        elif not row_filter.any():
            return
        if "Log" not in df:
            df["Log"] = "[]"
        else:
            df["Log"] = df["Log"].astype("string", copy=False).fillna("[]")
            df["Log"] = df["Log"].str.replace("^$", r"[]", regex=True)
        pp(f"[bold green]Logging:[/bold green] [italic]{processing}")
        log_function = partial(Base.format_log, processing=processing, column=column)
        if column is not None:
            df_logged = df.loc[row_filter, ["Log", column]].copy()
            df_logged[column] = (
                df_logged[column].astype("string", copy=False).fillna("")
            )
        else:
            df_logged = df.loc[row_filter, ["Log"]]
        df.loc[row_filter, "Log"] = df_logged.progress_apply(log_function, axis=1)

    @staticmethod
    def format_log(
        row: pd.Series,
        processing: str,
        column: Union[str, None] = None,
    ) -> str:
        """Translate log string into dict, update it and reformats it a log message"""
        log = listify(eval(row.loc["Log"]))
        new_log = {"Processamento": processing}
        if column is not None:
            new_log.update({"Coluna": column, "Original": row.loc[column]})
        log.append(new_log)
        return json.dumps(log, ensure_ascii=False)

    @staticmethod
    def split_designacao(
        df: pd.DataFrame,  # DataFrame com coluna original DesignacaoEmissao
    ) -> (
        pd.DataFrame
    ):  # DataFrame com novas colunas Largura_Emissão(kHz) e Classe_Emissão
        """Parse a bandwidth string and create new columns for bandwidth and emission class"""
        # split then explode
        df["Temp"] = (
            df["Designação_Emissão"]
            .str.strip()
            .str.replace(",", " ")
            .str.strip()
            .str.upper()
            .str.split()
        )

        df = df.explode("Temp", ignore_index=True)

        # Removes empty rows
        df = df[df["Temp"] != "/"]
        df["Temp"] = df["Temp"].astype("string", copy=False).fillna("")

        # Apply the parse_bw function
        parsed_data = zip(*df["Temp"].apply(Base.parse_bw))

        df["Largura_Emissão(kHz)"], df["Classe_Emissão"] = parsed_data
        df["Largura_Emissão(kHz)"] = df["Largura_Emissão(kHz)"].astype(
            "string", copy=False
        )
        df["Classe_Emissão"] = df["Classe_Emissão"].astype("string", copy=False)
        return df.drop(["Designação_Emissão", "Temp"], axis=1)

    @staticmethod
    def convert_frequency(df: pd.DataFrame, frequency_col: str = "Frequência", unit_col: str = "Unidade") -> pd.DataFrame:
        """Convert frequency values based on their units (kHz, MHz, GHz, etc.) to MHz"""
        df = df.copy()
        # Convert to numeric first
        df[frequency_col] = pd.to_numeric(df[frequency_col], errors="coerce")
        
        # Handle different units if unit column exists
        if unit_col in df.columns:
            # Convert kHz to MHz
            df.loc[df[unit_col] == "kHz", frequency_col] = df.loc[
                df[unit_col] == "kHz", frequency_col
            ].apply(lambda x: float(Decimal(x) / Decimal(1000)) if pd.notna(x) else x)
            
            # Convert GHz to MHz
            df.loc[df[unit_col] == "GHz", frequency_col] = df.loc[
                df[unit_col] == "GHz", frequency_col
            ].apply(lambda x: float(Decimal(x) * Decimal(1000)) if pd.notna(x) else x)
            
            # Remove unit column as it's no longer needed
            df.drop(unit_col, axis=1, inplace=True, errors='ignore')
        
        return df

    @staticmethod
    def handle_null_frequencies(df: pd.DataFrame, frequency_col: str = "Frequência", log_message: str = "Coluna Frequência com valores nulos") -> pd.DataFrame:
        """Remove rows with null frequencies and log them"""
        df = df.copy()
        discarded = df[df[frequency_col].isna()]
        if not discarded.empty:
            processing = log_message
            Base.register_log(discarded, processing)
            # TODO: Implement discarded data handling if needed
        df.dropna(subset=[frequency_col], inplace=True)
        return df

    @staticmethod
    def set_data_source(df: pd.DataFrame, source: str, source_col: str = "Fonte") -> pd.DataFrame:
        """Set the data source identifier"""
        df = df.copy()
        df[source_col] = source
        df[source_col] = df[source_col].astype("string", copy=False)
        return df

    @staticmethod
    def set_multiplicity(df: pd.DataFrame, multiplicity: str = "1", multiplicity_col: str = "Multiplicidade") -> pd.DataFrame:
        """Set the multiplicity value"""
        df = df.copy()
        df[multiplicity_col] = multiplicity
        df[multiplicity_col] = df[multiplicity_col].astype("string", copy=False)
        return df

    @staticmethod
    def format_date_column(df: pd.DataFrame, date_col: str = "Validade_RF") -> pd.DataFrame:
        """Format date column to YYYY-MM-DD format"""
        df = df.copy()
        if date_col in df.columns:
            df[date_col] = df[date_col].astype("string", copy=False).str.slice(0, 10)
        return df

    @staticmethod
    def parse_emission_designation(df: pd.DataFrame, service_col: str = "Serviço", bw_map: dict = None) -> pd.DataFrame:
        """Parse emission designation based on service mapping"""
        df = df.copy()
        if bw_map and service_col in df.columns:
            df["Designação_Emissão"] = df[service_col].fillna("").map(bw_map)
            df = Base.split_designacao(df)
        return df

    @staticmethod
    def convert_frequency(df: pd.DataFrame, frequency_col: str = "Frequência", unit_col: str = "Unidade") -> pd.DataFrame:
        """Convert frequency values based on their units (kHz, MHz, GHz, etc.) to MHz"""
        df = df.copy()
        # Convert to numeric first
        df[frequency_col] = pd.to_numeric(df[frequency_col], errors="coerce")
        
        # Handle different units if unit column exists
        if unit_col in df.columns:
            # Convert kHz to MHz
            df.loc[df[unit_col] == "kHz", frequency_col] = df.loc[
                df[unit_col] == "kHz", frequency_col
            ].apply(lambda x: float(Decimal(x) / Decimal(1000)) if pd.notna(x) else x)
            
            # Convert GHz to MHz
            df.loc[df[unit_col] == "GHz", frequency_col] = df.loc[
                df[unit_col] == "GHz", frequency_col
            ].apply(lambda x: float(Decimal(x) * Decimal(1000)) if pd.notna(x) else x)
            
            # Remove unit column as it's no longer needed
            df.drop(unit_col, axis=1, inplace=True, errors='ignore')
        
        return df

    @staticmethod
    def handle_null_frequencies(df: pd.DataFrame, frequency_col: str = "Frequência", log_message: str = "Coluna Frequência com valores nulos") -> pd.DataFrame:
        """Remove rows with null frequencies and log them"""
        df = df.copy()
        discarded = df[df[frequency_col].isna()]
        if not discarded.empty:
            processing = log_message
            Base.register_log(discarded, processing)
            # TODO: Implement discarded data handling if needed
        df.dropna(subset=[frequency_col], inplace=True)
        return df

    @staticmethod
    def set_data_source(df: pd.DataFrame, source: str, source_col: str = "Fonte") -> pd.DataFrame:
        """Set the data source identifier"""
        df = df.copy()
        df[source_col] = source
        df[source_col] = df[source_col].astype("string", copy=False)
        return df

    @staticmethod
    def set_multiplicity(df: pd.DataFrame, multiplicity: str = "1", multiplicity_col: str = "Multiplicidade") -> pd.DataFrame:
        """Set the multiplicity value"""
        df = df.copy()
        df[multiplicity_col] = multiplicity
        df[multiplicity_col] = df[multiplicity_col].astype("string", copy=False)
        return df

    @staticmethod
    def format_date_column(df: pd.DataFrame, date_col: str = "Validade_RF") -> pd.DataFrame:
        """Format date column to YYYY-MM-DD format"""
        df = df.copy()
        if date_col in df.columns:
            df[date_col] = df[date_col].astype("string", copy=False).str.slice(0, 10)
        return df

    @staticmethod
    def parse_emission_designation(df: pd.DataFrame, service_col: str = "Serviço", bw_map: dict = None) -> pd.DataFrame:
        """Parse emission designation based on service mapping"""
        df = df.copy()
        if bw_map and service_col in df.columns:
            df["Designação_Emissão"] = df[service_col].fillna("").map(bw_map)
            df = Base.split_designacao(df)
        return df

    @property
    def stem(self) -> str:
        """The stem name for files related to this data source"""
        raise NotImplementedError("Subclasses devem setar a propriedade stem")

    def extract_raw_data(self) -> pd.DataFrame:
        """Extract raw data from the database"""
        raise NotImplementedError("Subclasses devem implementar o método extract_raw_data")

    def format_data(self, df: pd.DataFrame) -> pd.DataFrame:
        """Format the raw data into the final structure"""
        raise NotImplementedError("Subclasses devem implementar o método format_data")

    def process_data(self) -> pd.DataFrame:
        """Process the raw data through extraction and formatting"""
        # Extract raw data
        raw_df = self.extract_raw_data()
        
        # Save raw data if not reading from cache
        if not self.read_cache:
            self._save(raw_df.drop("Log", axis=1, errors='ignore'), self.folder, f"{self.stem}_raw")
        
        # Format the data
        formatted_df = self.format_data(raw_df)
        
        return formatted_df

    def update(self):
        """Update the cached dataframe with newly processed data"""
        self.df = self.process_data()

    def save(self, folder: Union[str, Path, None] = None):
        """Save the processed dataframe to a parquet file"""
        if folder is None:
            folder = self.folder
        self._save(self.df, folder, self.stem)