"""Módulo para encapsular a criação de conectores de banco com o intuito de serem usados por composição nas classes de extração de dados

Docs: https://InovaFiscaliza.github.io/rfdatahub/connectors.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/01a_connectors.ipynb.

# %% auto #0
__all__ = ['DBConnector', 'SQLServer', 'MongoDB']

# %% ../../nbs/01a_connectors.ipynb #86b65165
from concurrent.futures import ThreadPoolExecutor
from dataclasses import dataclass

import pyodbc
from pymongo import MongoClient

# from motor.motor_asyncio import AsyncIOMotorClient

# %% ../../nbs/01a_connectors.ipynb #e486ae38
@dataclass
class DBConnector:
    def connect(self):
        raise NotImplementedError

    def get_parallel_connections(self, n):
        # This method returns a list of n pyodbc connection objects in parallel
        with ThreadPoolExecutor(max_workers=n) as executor:
            futures = [executor.submit(self.connect) for _ in range(n)]
            return [future.result() for future in futures]

# %% ../../nbs/01a_connectors.ipynb #660b3c1c
@dataclass
class SQLServer(DBConnector):
    sql_params: dict

    def connect(self):
        # This method returns a pyodbc connection object according to the platform
        connection_string = f"""Driver={self.sql_params.get('driver')};
                                Server={self.sql_params.get('server')};
                                Database={self.sql_params.get('database')};
                                Encrypt=no;"""
        if self.sql_params.get("trusted_conn"):
            connection_string += f"""MultipleActiveResultSets={self.sql_params.get('mult_results')};
                                  Trusted_Connection=yes;"""
        else:
            connection_string += f"""UID={self.sql_params.get('username')};
                                  PWD={self.sql_params.get('password')};
                                  Trusted_Connection=no;"""
        try:
            return pyodbc.connect(
                connection_string, timeout=self.sql_params.get("timeout", 10000)
            )
        except pyodbc.OperationalError as e:
            raise ConnectionError(
                "Não foi possível abrir uma conexão com o SQL Server. Esta conexão somente funciona da rede cabeada!"
            ) from e

# %% ../../nbs/01a_connectors.ipynb #4bbc9031
@dataclass
class MongoDB(DBConnector):
    mongo_uri: str

    def connect(self):
        # This method returns a connected AsyncIOMotorClient object
        return MongoClient(self.mongo_uri)
