# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/01a_connectors.ipynb.

# %% auto 0
__all__ = ["SQLServer", "MongoDB"]

# %% ../../nbs/01a_connectors.ipynb 3
from concurrent.futures import ThreadPoolExecutor
from dataclasses import dataclass
from typing import Union, Dict, Any
import pandas as pd

import pyodbc
from pymongo import MongoClient

from .base_refactored import DatabaseConnector

# %% ../../nbs/01a_connectors.ipynb 7
@dataclass
class SQLServer(DatabaseConnector):
    """Class for connecting to SQL Server"""

    sql_params: dict

    def connect(self):
        """This method returns a pyodbc connection object according to the os platform"""
        connection_string = f"""Driver={self.sql_params.get("driver")};
								Server={self.sql_params.get("server")};
								Database={self.sql_params.get("database")};
								Encrypt=no;"""
        if self.sql_params.get("trusted_conn"):
            connection_string += f"""MultipleActiveResultSets={self.sql_params.get("mult_results")};
								  Trusted_Connection=yes;"""
        else:
            connection_string += f"""UID={self.sql_params.get("username")};
								  ******"password")};
								  Trusted_Connection=no;"""
        try:
            return pyodbc.connect(
                connection_string, timeout=self.sql_params.get("timeout", 10000)
            )
        except pyodbc.OperationalError as e:
            raise ConnectionError(
                "Não foi possível abrir uma conexão com o SQL Server. Esta conexão somente funciona da rede cabeada!"
            ) from e

    def extract_data(self, query: str, **kwargs) -> pd.DataFrame:
        """Extract data from SQL Server using the provided query"""
        conn = self.connect()
        try:
            return pd.read_sql_query(query, conn, dtype="string")
        finally:
            conn.close()


# %% ../../nbs/01a_connectors.ipynb 9
@dataclass
class MongoDB(DatabaseConnector):
    """Class for connecting to MongoDB"""

    mongo_uri: str

    def connect(self):
        """This method returns a connected MongoClient object"""
        return MongoClient(self.mongo_uri)

    def extract_data(self, query: Dict[str, Any], **kwargs) -> pd.DataFrame:
        """Extract data from MongoDB using the provided query"""
        client = self.connect()
        try:
            database = client[query.get("database", "sms")]
            collection = database[query.get("collection")]
            pipeline = query.get("pipeline", [])
            return pd.DataFrame(
                list(collection.aggregate(pipeline)), copy=False, dtype="string"
            )
        finally:
            client.close()