"""Este módulo concentra as constantes, funções de carga, processamento, mesclagem e salvamento de dados aeronáuticos provenientes do Software Frequency Finder da ICAO

Docs: https://InovaFiscaliza.github.io/rfdatahub/icao.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/02a_icao.ipynb.

# %% auto #0
__all__ = ['COLS_NAV', 'COLS_COM', 'UNIQUE_COLS', 'convert_latitude', 'convert_longitude', 'map_channels', 'get_icao']

# %% ../../nbs/02a_icao.ipynb #e742da5c
import os
from pathlib import Path
from typing import Iterable

import pandas as pd
from dotenv import find_dotenv, load_dotenv
from ..constants import PATH_NAV, PATH_COM, VOR_ILS_DME

load_dotenv(find_dotenv(), override=True)

# %% ../../nbs/02a_icao.ipynb #6e86a985
COLS_NAV = ["Frequency", "Latitude", "Longitude", "Facility", "Location", "NS", "WE"]
COLS_COM = ["Frequency", "CoordLat", "CoordLong", "DOC", "Location", "NS", "WE"]
UNIQUE_COLS = ["Frequência", "Latitude", "Longitude"]

# %% ../../nbs/02a_icao.ipynb #bb68f1cd
def convert_latitude(
    lat: str,  # Latitude
    hemisphere: str,  # Hemisfério: N | S
) -> float:
    """Converte a Latitude para formato decimal"""
    multiplier = 1 if hemisphere == "N" else -1
    return multiplier * (
        float(lat[:2]) + float(lat[3:5]) / 60 + float(lat[6:8]) / 3600.0
    )


def convert_longitude(
    lon: str,  # Longitude
    hemisphere: str,  # Hemisfério: W | E
) -> float:
    """Converte a longitude para formato decimal"""

    multiplier = 1 if hemisphere == "E" else -1
    return multiplier * (
        float(lon[1:3]) + float(lon[4:6]) / 60 + float(lon[7:9]) / 3600.0
    )

# %% ../../nbs/02a_icao.ipynb #16fe7b6a
def _read_df(
    path: str,  # Caminho do arquivo
    usecols: Iterable[str],  # Subconjunto de colunas do arquivo
) -> pd.DataFrame:  # Dataframe formatado
    # sourcery skip: use-fstring-for-concatenation
    """Lê o DataFrame no caminho `path`, filtra as colunas `usecols` e o retorna formatado"""
    df = pd.read_csv(path, dtype="string")[usecols]
    df.columns = COLS_NAV
    df["Latitude"] = df.apply(
        lambda x: convert_latitude(x["Latitude"], x["NS"]), axis=1
    )
    df["Longitude"] = df.apply(
        lambda x: convert_longitude(x["Longitude"], x["WE"]), axis=1
    )
    df["Description"] = df.Facility + ", " + df.Location
    df["Fonte"] = "ICAO"
    df = df[["Frequency", "Latitude", "Longitude", "Description", "Fonte"]]
    df.columns = ["Frequência", "Latitude", "Longitude", "Entidade", "Fonte"]
    return df

# %% ../../nbs/02a_icao.ipynb #eb29deaa
def map_channels(
    df: pd.DataFrame,  # DataFrame dos dados de origem
    origem: str,  # Descrição da emissão a ser substituída
) -> pd.DataFrame:
    """Mapeia os canais contidos em `df` e adiciona os registros ILS/DME caso houver"""
    chs = pd.read_csv(VOR_ILS_DME, dtype="string", dtype_backend="pyarrow")
    for row in df[df.Entidade.str.contains("ILS|DME")].itertuples():
        if not (ch := chs[(chs.VOR_ILSloc == row.Frequência)]).empty:
            for i, c in enumerate(ch.values[0][2:]):
                if pd.notna(c):
                    if i == 0:
                        freq_type = "ILS glide path"
                    elif i == 1:
                        freq_type = "Airbone DME"
                    elif i == 2:
                        freq_type = "Ground-based DME"
                    else:
                        raise ValueError("No additional frequency to map on channel")
                    entidade = row.Entidade + f"({freq_type})"
                    df.loc[len(df)] = [
                        c,
                        row.Latitude,
                        row.Longitude,
                        entidade,
                        f"{origem}-CANALIZACAO-VOR/ILS/DME",
                    ]
    return df

# %% ../../nbs/02a_icao.ipynb #8cd6581d
def get_icao() -> (
    pd.DataFrame
):  # DataFrame com frequências, coordenadas e descrição das estações
    """Lê, concatena e pós-processa os arquivos do ICAO"""
    df = pd.concat(
        _read_df(p, c) for p, c in zip([PATH_NAV, PATH_COM], [COLS_NAV, COLS_COM])
    )
    df = df.astype("string")
    return map_channels(df, "ICAO").drop_duplicates(UNIQUE_COLS, ignore_index=True)
