name: Deploy to GitHub Pages
on:
  push:
    branches: [master, dev]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: AnswerDotAI/workflows/quarto-ghp3@master

